### ISSUE TITLE
Fishbot Aiming

### ISSUE THREAD

**Issue by Venomexeno** [mmtcoder/Metin2-FishBot-AutoFish-Balikbotu-otomatik-balik-botu-metin2-level-botu-metin2-enerji-botu#1]
lütfen fishbot mini oyun dedektörünü geliştirebilir misiniz çünkü bazen balığa çarpmıyor, 300 milisaniye boyunca dairenin içinde durursa algılama gibi bir şey yapabilir misiniz sonra üzerine tıklayabilir misiniz veya tahmini yön yapabilir ve hareket halindeyken balığa çarptığından emin olmak için 1 adım daha atarak ardından tıklayabilir misiniz

**Comment by mmtcoder** [comment]
Yavaş bilgisayar için yavaş pc ayrı buton ekledim diğeri senin dediğin gibi
balığın gitme yönünü tahmin ederek yaptım. Ben botu geliştirmeyi 2 ay önce
bıraktım

**Comment by Venomexeno** [comment]
Tamam, çok teşekkür ederim ve sıkı çalışmanızı takdir ediyorum ❤️
